---

services:
  livebook:
    build: .
    container_name: livebook
    ports:
      - '4000:4000'
      - '8080:8080'
      - '8081:8081'
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
    volumes:
      - ./tmp:/tmp
      - ./lambda:/lambda
      - ./sagemaker:/sagemaker
      - //var/run/docker.sock:/var/run/docker.sock
