---

services:
  livebook_with_db:
    build: .
    container_name: livebook_with_db
    ports:
      - '4000:4000'
      - '8080:8080'
      - '8081:8081'
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
    volumes:
      - ./tmp:/tmp
      - ./lambda:/lambda
      - ./sagemaker:/sagemaker
      - //var/run/docker.sock:/var/run/docker.sock

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_for_livebook
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_for_livebook:/var/lib/postgresql/data

  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    container_name: sql_server_for_livebook
    platform: linux/amd64
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=msSql_1234
    volumes:
      - sql_server_for_livebook:/var/opt/mssql

volumes:
  postgres_for_livebook:
  sql_server_for_livebook:
