---

version: '3.2'

services:
  livebook_with_db:
    build: .
    container_name: livebook_with_db
    ports:
      - '4000:4000'
      - '8080:8080'
      - '8081:8081'
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
    volumes:
      - ./tmp:/tmp
      - ./lambda:/lambda
      - ./sagemaker:/sagemaker
      - //var/run/docker.sock:/var/run/docker.sock

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_for_livebook
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_for_livebook:/var/lib/postgresql/data

volumes:
  postgres_for_livebook:
