---

services:
  livebook_charms:
    build:
      context: .
      dockerfile: Dockerfile.charms
    container_name: livebook_charms
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./tmp:/tmp
