FROM postgres:16.8-bullseye

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y postgresql-16-pgvector \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
