---

services:
  livebook_charms:
    build:
      context: .
      dockerfile: Dockerfile.charms
    container_name: livebook_charms
    ports:
      - '4000:4000'
      - '8080:8080'
      - '8081:8081'
    environment:
      - HTTP_PROXY
      - HTTPS_PROXY
    volumes:
      - ./tmp:/tmp
