# fly.toml app configuration file generated for livebook-rwakabay-gpu on 2024-02-16T09:24:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'livebook-rwakabay-gpu'
primary_region = 'ord'

[build]
  image = 'ghcr.io/livebook-dev/livebook:latest-cuda12.1'

[env]
  BUMBLEBEE_CACHE_DIR = '/data/cache/bumblebee'
  ELIXIR_ERL_OPTIONS = '-proto_dist inet6_tcp +sssdio 128'
  LIVEBOOK_DATA_PATH = '/data'
  LIVEBOOK_HOME = '/data'
  LIVEBOOK_IP = '::'
  LIVEBOOK_ROOT_PATH = '/data'
  PORT = '8080'
  XLA_CACHE_DIR = '/data/cache/xla'
  XLA_TARGET = 'cuda120'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'a100-40gb'
  cpu_kind = 'performance'
  cpus = 8
  memory_mb = 32768
