---

services:
  web:
    container_name: phoenix
    build: .
    platform: linux/amd64
    ports:
      - '8082:8080'
    command: serve
    volumes:
      - ./tmp:/tmp
      - ./models:/opt/ml/model
